server:
  port: 9999
  servlet:
    context-path: /teams
spring:
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: UTF-8
  mvc:
    static-path-pattern: /**
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://43.138.204.211:3307/self_student_teams?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxWait: 60000
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl